In [70]:
#preprocessing2

In [71]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [72]:
df=pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [73]:
len(df)

891

In [74]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [75]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [76]:
dataset = df
titles = {"Mr": 1, "Miss": 2, "Mrs": 3, "Master": 4, "Rare": 5}

# extract titles
dataset['Title'] = df.Name.str.extract(' ([A-Za-z]+)\.', expand=False)
# replace titles with a more common title or as Rare
dataset['Title'] = dataset['Title'].replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr',\
                                        'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
dataset['Title'] = dataset['Title'].replace('Mlle', 'Miss')
dataset['Title'] = dataset['Title'].replace('Ms', 'Miss')
dataset['Title'] = dataset['Title'].replace('Mme', 'Mrs')
# convert titles into numbers
dataset['Title'] = dataset['Title'].map(titles)
# filling NaN with 0, to get safe
dataset['Title'] = dataset['Title'].fillna(0)
dataset = dataset.drop(['Name'], axis=1)
#test_df = test_df.drop(['Name'], axis=1)

In [77]:
dataset.head(2)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Ticket  \
0            1         0       3    male  22.0      1      0  A/5 21171   
1            2         1       1  female  38.0      1      0   PC 17599   

      Fare Cabin Embarked  Title  
0   7.2500   NaN        S      1  
1  71.2833   C85        C      3

In [78]:
genders = {"male": 0, "female": 1}
dataset['Sex'] = dataset['Sex'].map(genders)

In [79]:
dataset =dataset.drop(['Ticket'], axis=1)


In [80]:
ports = {"S": 0, "C": 1, "Q": 2}
dataset['Embarked'] = dataset['Embarked'].map(ports)


In [81]:
dataset.head(2)

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare Cabin  \
0            1         0       3    0  22.0      1      0   7.2500   NaN   
1            2         1       1    1  38.0      1      0  71.2833   C85   

   Embarked  Title  
0       0.0      1  
1       1.0      3

In [82]:
dataset =dataset.drop(['Cabin'], axis=1)

#Age:
Now we need to convert the ‘age’ feature. First we will convert it from float into integer. 
Then we will create the new ‘AgeGroup” variable, by categorizing every age into a group
. Note that it is important to place attention on how you form these groups, 
since you don’t want for example that 80% of your data falls into group 1.

In [83]:
mean = df["Age"].mean()
std =  df["Age"].std()

is_null = dataset["Age"].isnull().sum()
# compute random numbers between the mean, std and is_null
rand_age = np.random.randint(mean - std, mean + std, size = is_null)
# fill NaN values in Age column with random values generated
age_slice = dataset["Age"].copy()
age_slice[np.isnan(age_slice)] = rand_age
dataset["Age"] = age_slice
dataset["Age"] = dataset["Age"].astype(int)
dataset["Age"].isnull().sum()



0

In [84]:
dataset.loc[ dataset['Age'] <= 11, 'Age'] = 0
dataset.loc[(dataset['Age'] > 11) & (dataset['Age'] <= 18), 'Age'] = 1
dataset.loc[(dataset['Age'] > 18) & (dataset['Age'] <= 22), 'Age'] = 2
dataset.loc[(dataset['Age'] > 22) & (dataset['Age'] <= 27), 'Age'] = 3
dataset.loc[(dataset['Age'] > 27) & (dataset['Age'] <= 33), 'Age'] = 4
dataset.loc[(dataset['Age'] > 33) & (dataset['Age'] <= 40), 'Age'] = 5
dataset.loc[(dataset['Age'] > 40) & (dataset['Age'] <= 66), 'Age'] = 6
dataset.loc[ dataset['Age'] > 66, 'Age'] = 6


In [85]:
dataset.head(1)

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked  \
0            1         0       3    0    2      1      0  7.25       0.0   

   Title  
0      1

Fare:
For the ‘Fare’ feature, we need to do the same as with the ‘Age’ feature. 
But it isn’t that easy, because if we cut the range of the fare values into a few equally big categories,
80% of the values would fall into the first category. Fortunately, 
we can use sklearn “qcut()” function, that we can use to see, how we can form the categories.

In [86]:
dataset.loc[ dataset['Fare'] <= 7.91, 'Fare'] = 0
dataset.loc[(dataset['Fare'] > 7.91) & (dataset['Fare'] <= 14.454), 'Fare'] = 1
dataset.loc[(dataset['Fare'] > 14.454) & (dataset['Fare'] <= 31), 'Fare']   = 2
dataset.loc[(dataset['Fare'] > 31) & (dataset['Fare'] <= 99), 'Fare']   = 3
dataset.loc[(dataset['Fare'] > 99) & (dataset['Fare'] <= 250), 'Fare']   = 4
dataset.loc[ dataset['Fare'] > 250, 'Fare'] = 5
dataset['Fare'] = dataset['Fare'].astype(int)

Creating new Features
I will add two new features to the dataset, that I compute out of other features.

In [87]:
dataset['Age_Class']= dataset['Age']* dataset['Pclass']

In [88]:
dataset.head(1)

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked  \
0            1         0       3    0    2      1      0     0       0.0   

   Title  Age_Class  
0      1          6

In [89]:
dataset['relatives']=dataset['SibSp']+dataset['Parch']

In [90]:
dataset.head(1)

PassengerId  Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked  \
0            1         0       3    0    2      1      0     0       0.0   

   Title  Age_Class  relatives  
0      1          6          1

In [91]:
dataset['Fare_Per_Person'] = dataset['Fare']/(dataset['relatives']+1)
dataset['Fare_Per_Person'] = dataset['Fare_Per_Person'].astype(int)

In [92]:
dataset["Embarked"].fillna(value = 0,inplace = True)

In [93]:

y_sm=dataset['Survived']
df=dataset.drop(columns='Survived')

In [94]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df, y_sm, test_size=0.2, random_state=15,stratify=y_sm )


In [95]:
#train_data= pd.concat([X_train, y_train], axis=1)
#test_data = pd.concat([X_test, y_test], axis=1)

In [96]:
#train_data.to_csv('processed_train2.csv',index=False)
#test_data.to_csv('processed_test2.csv',index=False)

In [97]:
y_sm.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [98]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [99]:
model.fit(df,y_sm)

GaussianNB()

In [102]:
model.score(X_test,y_test)

0.8268156424581006

In [103]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),df,y_sm, cv=5)

array([0.72067039, 0.74157303, 0.79213483, 0.79775281, 0.84269663])

In [104]:
###Multinomial Naive Bayes

In [114]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB(alpha = 0.2) ####laplace vs lidstone smoothing
model.fit(df,y_sm)
model.score(X_test,y_test)

0.7541899441340782

In [112]:
from sklearn.model_selection import cross_val_score
cross_val_score(MultinomialNB(),df,y_sm, cv=10)

array([0.62222222, 0.69662921, 0.6741573 , 0.78651685, 0.74157303,
       0.74157303, 0.76404494, 0.73033708, 0.78651685, 0.76404494])

In [116]:
from sklearn.naive_bayes import ComplementNB
model = ComplementNB()
model.fit(df,y_sm)
model.score(X_test,y_test)

0.7430167597765364

In [117]:
from sklearn.naive_bayes import CategoricalNB
model = CategoricalNB()
model.fit(df,y_sm)
model.score(X_test,y_test)

0.8547486033519553

In [120]:
from sklearn.model_selection import cross_val_score
cross_val_score(CategoricalNB(),df,y_sm, cv=5)

C:\Users\Dell\miniconda3\lib\site-packages\sklearn\model_selection\_validation.py:696: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\Users\Dell\miniconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 687, in _score
    scores = scorer(estimator, X_test, y_test)
  File "C:\Users\Dell\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 90, in __call__
    score = scorer(estimator, *args, **kwargs)
  File "C:\Users\Dell\miniconda3\lib\site-packages\sklearn\metrics\_scorer.py", line 397, in _passthrough_scorer
    return estimator.score(*args, **kwargs)
  File "C:\Users\Dell\miniconda3\lib\site-packages\sklearn\base.py", line 500, in score
    return accuracy_score(y, self.predict(X), sample_weight=sample_weight)
  File "C:\Users\Dell\miniconda3\lib\site-packages\sklearn\naive_bayes.py", line 75, in predict
    jll = self._joint_log_likelihood

array([0.7150838 , 0.78651685, 0.80337079,        nan,        nan])